# Generated by Django 3.1.1 on 2020-09-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=50)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
