# Generated by Django 3.1.1 on 2020-09-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=50)),
                ('image', models.FilePathField(path='static/projects/images/portfolio/')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
