# Generated by Django 3.1.1 on 2020-09-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200918_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/static/projects/images/portfolio'),
        ),
    ]
