# Generated by Django 3.1.1 on 2020-11-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200926_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='report',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
