# Generated by Django 3.1.1 on 2020-11-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201117_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesAdmin',
        ),
        migrations.AddField(
            model_name='project',
            name='adminupload',
            field=models.FileField(default='file', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank='False', default='image', upload_to='media'),
        ),
    ]
