# Generated by Django 3.1.1 on 2020-11-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201117_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='adminupload',
            field=models.FileField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank='False', default='', upload_to='media'),
        ),
    ]
