# Generated by Django 3.1.1 on 2020-11-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20201117_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(default='', upload_to='media')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
