# Generated by Django 3.1.1 on 2020-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200922_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FilePathField(path='/projects/images/portfolio'),
        ),
    ]
